services:
  e-commerce-admin-frontend:
    build:
      context: ./e-commerce-admin-frontend
      dockerfile: Dockerfile
    image: e-commerce-admin-frontend
    ports:
      - "${ADMIN_FRONTEND_PORT}:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:${USER_SERVICE_BACKEND_PORT}
    volumes:
      - ./e-commerce-admin-frontend:/app
      - /app/node_modules

  e-commerce-buyer-frontend:
    build:
      context: ./e-commerce-buyer-frontend
      dockerfile: Dockerfile
    image: e-commerce-buyer-frontend
    ports:
      - "${BUYER_FRONTEND_PORT}:5174"
    environment:
      - VITE_BACKEND_URL=http://localhost:${USER_SERVICE_BACKEND_PORT}
    volumes:
      - ./e-commerce-buyer-frontend:/app
      - /app/node_modules

  e-commerce-user-service-backend:
    build: ./e-commerce-user-service-backend
    image: e-commerce-user-service-backend
    ports:
      - "${USER_SERVICE_BACKEND_PORT}:${USER_SERVICE_BACKEND_PORT}"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=${USER_SERVICE_BACKEND_PORT}
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - data_backup:/var/opt/mssql

volumes:
  data_backup:
